"""add photo background

Revision ID: beec52dedff2
Revises: 2a069759b8b9
Create Date: 2020-09-26 21:40:04.876653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beec52dedff2'
down_revision = '2a069759b8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upvotes', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upvotes', sa.Column('likes', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
